services:
  api-products-h2:
    image: "springboot-graalvm:h2"
    ports:
      - "8180:8080"
    networks:
      - native-image-network
    build:
      context: .
      dockerfile: Dockerfile

networks:
  native-image-network:
    driver: bridge
